version: '3.8'

services:
  neezs-memory:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ZEP_API_KEY=${ZEP_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
